<?xml version="1.0"?>
<package format="3">
  <name>pennair_shapes</name>
  <version>1.0.0</version>
  <description>Shape detection on a video stream, published on ROS 2 topics.</description>
  <maintainer email="raghavdaga2007@gmail.com">Raghav</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
